<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>promise-demo-isAsync</title>
</head>
<body>

</body>
<script src="../jquery-3.2.1.min.js"></script>
<script type="text/javascript">

    function asyncFunction() {
        return new Promise(function (resolve, reject) {
//            while(true){
//                console.log("异步函数执行中");
//
//            }

            resolve("hello world");
        });
    }
    asyncFunction().then(function (value) {
        console.log(value)
    }).catch(function (error) {
        console.log(error);
    });
    console.log("4545");
    /**
     * 浏览器端-输出结果
     * 一直在输出 "异步函数执行中"  而未输出4545  这是在浏览器端测试的结果 证明promise里的函数逻辑还是在走主线程，跟settimeout类似。
     *
     * node端 输出结果与浏览器端一致
     * */
</script>
</html>